# run in a container
sudo: false

language: java
jdk: openjdk8

env:
  global:
    # OSSRH_USERNAME 
    - secure: "BdQOt59ZBPulO5KRkJosbxlH7J6GVelcjHnZkgt1jeGqf+JhOvCD5Jucvm+ZK2L0ojVsVp7j0dN2PftI3GF0mL/coICTnayvEVo8Mfp8Jl4uorH9RRXA/ju5MdPUp+EOShmOc6LW0PUjGAzF9HfpKvyQ9/hI0n78ToDR9EncrCzfOs4g1BVAxSVso0JGhArx0nMf9KjTrBNgzTavOUcEOloQRRtg4O/oWRkeMbUCxF3pnJchTKWXFB9k/0pERR8aYAVggBoAdi51VO/yUhnvkqxVfhXvHHT7FrLbXGnsrFDNYR0ZovWBIWuqdCuGTvnOYX/DT8wPGTHTAe9/NV/6nBfDe5LSaEjqEe+lsPEUBwLgNntbfT2gOkPFzWyXxIOLk2lXQobtxG82ivpyaElOEt9noRkRbuCJuWTxepbHu89Ry76fb+mpXYyvlfwDTsTCeKfFYpycV37pM/rQmDsCc9T5N0KH4wf9zeLzityGRVPnNyurl/NT5DDefNZNvUTyOYsZSDFBVvoimRJYIjfcI1472UqcT0RnbUjxbh8mV8yJFmuKXdCjiwDBf57nrB8ZUFgc4jo1fP4KIUlrNGSt2S1gtJBKir3SUyhvjXRqniFPuSmWGeJOwtg0hDifiSDTubcoTfRjEiE7v3ZKcp0q6brm7HKcl+pXl32JGy/fJqE="
    # OSSRH_PASSWORD
    - secure: "tpH5907oyGI2OrLx8jKwA/2If5K0TbDE7dtB0d2FpPwSrHkyX9/2v8G1Kk5pPlXvxv831V9PXGhvDwnQjhrhJPlHBsoUghCXJGizCstgr/fCEeYGkAlrzuq3KlvRd2FKgRZyMdGBvW0bZy5wxvk+yOOd23RAzdvjFomZgc2ZCpRwHqKGparf7IWQ68twr/MlwrKyoUPRQii8cicco9KjFgzZh+6fDfwLC5A75iGN8p7Hg/YQhPy8l6TLJalzLPlY0Q2EJzcqYixF3vAeam6+Qo6WhSpv6+7K3ybE+cvR045hLbhmH0LFQ3PFngDRVlLTjWnhi4GPVCpa/QrRsiNg6c0gRXFABJBrb2DL/UhRzp3LCqWbhXVKGMYY+MSKAvmr5RdaMuGkjr1FttPDmuAn2AKwkKn3kEQ2HCGWBLQmH9QuERdhUPrSOLmgc1SoWZdRVL9kDgpWqTGvZRRn4FhuYmxyMPx/i1kzO18/eLALcoLhNuwMtH/sa0hsxBOqPipGBUTjNLZUWOppnjPdDGiruXA7Hpn92XjP82EnwuALqHYkMdBb6UqeP403aMqXqSL4YE1C0nK5r+n8xPhiiaZoSyDRH9mw4qY7Z9U8YoiXqyQpxelJVdvQVDX5ZUJXJmWlQ2q3GVEhq6BpNZ9y5i0lABNWnJPP3ow05yPxC/RqzNQ="
    # GPG_KEYNAME
    - secure: "qaF7AiNEu6VYXaD98UUzKunzacogSKMuhmWMPExv454Rf/ElN5o1p6hVDWroMjVE4CVqz2GI8npJNq5B3HGECB9H5BunLIvg+f67HSUVGYUrrrzdiu/VpA3VJbU4stvGvUqcLdHY3wrMydQ5Xm8YGLL1zPn5ICw5IRfhNmCilviLCfChSQeh2IBf15MjTfiyMpZDJxkUwGduTdp7rq1ScKrIsvBsfsIagBahOQtggaTLe7cYt5c601PnSDfcdnY+fPni8rVkgxfrkDUoaBIMnLdl9Dcej0VpE5L3/c9RUNX6Nd/DfSSqe3cYJQ8Aig4hpD6PNxkE6zo4VAfXzqvkCWQQbQrhj13YaBlbse+4MM0ZuKzIJb626hauJ8KvnkzyBAHR1LH948MLRLsNdx5nI6eG3XZ0FiD7S7QiD4348ua+QEawxRn2NaxnzkqxtCyJvG+rAzU1QuRbH5ufeOpP1fGtLyhbtf16yLSEf7a69J3eDeJBe6W1yT0TJrtX/ghkgR1eVpD3Ys9hAT1OTrYfRjue2b+MThgH5OQRJAA+YmUQfgQmCgstmeU4SmOLiOZ3eivkYPTP93JouWfK0MkIttH8/Y2XXpbIApTxEHOas6F2OU4ja9QGiI/C6emuRXEEc0JiBu/znormbE2FU8FEST/HDtMpcErVY8TNVr0b68Y="
    # GPG_PASSPHRASE
    - secure: "UZJF2vhVBtJ5A7orpaOVQQSVFHW0aGB0hHpfONAD/nzs/xdQqZqd9GV9X6gldooBWM4j5NxkBE1r9h21wPPJjMXLO7swxUcTIf3P2y1CPpFumVZRa0DOGG+IQsjvzrE82z44n0rv3IT6tz9sGr2GW5/BdvT/lXn0+N5T9YShDaTCNEpJb89TkXTExlKmJFtZmnMU5SQk/S39HIiK28Ag6TZLLSXUtpiYJFyPPVwbcS1a5f+ATga2HIpoMDEfPARVb9XnqDJlZ9nNQbE69iUN0Sl7rTOwSZmUNp8umLz9HTdi5QoGgrteux3SdFYTH3gmwYAgZExD6JQZIMK8Tv3jn+Yshp+9ruloA3MEk9iVYgdl5QTPjjEOeaLsRSq6p03BXr0O6LnmvgYTiCLp6U8OJvclOHxUXkfdm8Gxz9Uo+sjU5d5WG8KhB9TOR53Autq4MZaRaopUEzxA+ioaakXMwfRb7biNGqNa6UusjHbncE+Z8rjSv1s5Lq4oeYC0Q/G3p6FK2IsLucmWsFBAO6m8muWTO7a8Y17mkAehGrKGhBCfj4N8Uehx7qM8SJYB85ZF7ic5zrkFfCDMIt0OyOVDplPCOu1l509sfJ8vUaslmFCPqX64VWuiOicfJ1c2tl5Uef8Y+4qkW5HCvxrj/xS4kUt6NHb0iw4518q8v9idwxc="

# skip the travis install step which actually do the whole "mvn install"!
install: true
# build with our settings
script: .travis/maven.sh clean verify -Pqulice

deploy:
  - provider: script
    script: .travis/maven.sh clean deploy
    on:
      condition: $(.travis/version.sh) = *SNAPSHOT
      branch: master
  - provider: script
    script: .travis/prepare-release.sh && .travis/maven.sh -Prelease clean deploy
    on:
      condition: $(.travis/version.sh) != *SNAPSHOT
      tags: true
